server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:file:./dim
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql=true:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

