server:
  port: 8090


datasource:
  url: jdbc:h2:file:./dim;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  username: sa
  password: password
  driverClassName: org.h2.Driver

jpa:
  dialect: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      format_sql=true:
  hibernate:
    ddl-auto: create
  show-sql: true
h2:
  console:
    enabled: true